# Generated by Django 5.0.14 on 2025-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cp_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('parameter', models.CharField(blank=True, max_length=100, null=True)),
                ('station_id', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('connection_status', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('tool', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cpreport',
                'managed': False,
            },
        ),
    ]
